#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

ENV_FILE=".env"
EXAMPLE_FILE=".env.example"

red()   { printf '\033[1;31m%s\033[0m\n' "$*"; }
green() { printf '\033[1;32m%s\033[0m\n' "$*"; }
info()  { printf '\033[1;34m→ %s\033[0m\n' "$*"; }
dim()   { printf '\033[2m%s\033[0m\n' "$*"; }

if [[ -f "$ENV_FILE" ]]; then
  red "An .env file already exists."
  printf "Overwrite it? [y/N] "
  read -r confirm
  if [[ "${confirm,,}" != "y" ]]; then
    echo "Aborted."
    exit 0
  fi
fi

info "Generating credentials"

# Secret (64 hex chars = 256 bits)
SECRET=$(openssl rand -hex 32)

# Username (adjective-noun format, easy to remember)
ADJECTIVES=(bold calm dark fast keen neat pure safe warm wise)
NOUNS=(admin chief guard pilot scout spark tower vault watch)
USERNAME="${ADJECTIVES[$((RANDOM % ${#ADJECTIVES[@]}))]}-${NOUNS[$((RANDOM % ${#NOUNS[@]}))]}"

# Password (24 chars, alphanumeric + symbols)
PASSWORD=$(openssl rand -base64 24 | tr -d '\n')

# Hash the password using Deno + the project's auth module
info "Hashing password (PBKDF2, 600k iterations)"
PASSWORD_HASH=$(deno eval "
  import { hashPassword } from './echelon-analytics/lib/auth.ts';
  console.log(await hashPassword('${PASSWORD//\'/\\\'}'));
")

# Generate .env from the example template
if [[ -f "$EXAMPLE_FILE" ]]; then
  cp "$EXAMPLE_FILE" "$ENV_FILE"
else
  red "Warning: $EXAMPLE_FILE not found — creating minimal .env"
  cat > "$ENV_FILE" <<'MINIMAL'
ECHELON_SECRET=
ECHELON_USERNAME=
ECHELON_PASSWORD_HASH=
MINIMAL
fi

# Inject generated values
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Prepend timestamp header
TMPFILE=$(mktemp)
cat > "$TMPFILE" <<HEADER
# Generated by scripts/configure.sh on ${TIMESTAMP}
#
HEADER
cat "$ENV_FILE" >> "$TMPFILE"
mv "$TMPFILE" "$ENV_FILE"

# Set values using sed (handles = delimiter)
sed -i "s|^ECHELON_SECRET=.*|ECHELON_SECRET=${SECRET}|" "$ENV_FILE"
sed -i "s|^ECHELON_USERNAME=.*|ECHELON_USERNAME=${USERNAME}|" "$ENV_FILE"
sed -i "s|^ECHELON_PASSWORD_HASH=.*|ECHELON_PASSWORD_HASH=${PASSWORD_HASH}|" "$ENV_FILE"

chmod 600 "$ENV_FILE"

echo ""
green "Configuration written to $ENV_FILE"
echo ""
echo "  ECHELON_SECRET       ${SECRET}"
echo "  ECHELON_USERNAME     ${USERNAME}"
echo "  ECHELON_PASSWORD     ${PASSWORD}"
dim  "  ECHELON_PASSWORD_HASH ${PASSWORD_HASH}"
echo ""
info "Save these credentials — the password cannot be recovered from the hash."
dim  "The .env file is chmod 600 and excluded from git."
